#!/usr/bin/env python

import os
import sys


def display(content, c1, c2):
    for line in content:
        for c in line:
            if c == '1':
                sys.stdout.write(c1)
            elif c == '0':
                sys.stdout.write(c2)
            elif (chr(ord('9') + 2)) >= c >= '2':
                sys.stdout.write(chr(ord(c) - 2))
            else:
                sys.stdout.write(c)
        sys.stdout.write("\n")


def pathfinding(content, f):
    l1 = list()
    l1.append(f)
    l2 = list()
    loop = chr(ord('2'))
    start = 0
    while len(l1) > 0:
        for m in l1[:]:
            if start == 1:
                if content[m[0]][m[1]] == 'P':
                    return content
                tmp = list(content[m[0]])
                tmp[m[1]] = loop
                content[m[0]] = ''.join(tmp)
            else:
                start = 1
            q = list()
            if (m[0] - 1) >= 0:
                q.append([m[0] - 1, m[1]])
            if (m[1] + 1) < len(content[m[0]]):
                q.append([m[0], m[1] + 1])
            if (m[0] + 1) < len(content):
                q.append([m[0] + 1, m[1]])
            if (m[1] - 1) >= 0:
                q.append([m[0], m[1] - 1])
            for point in q:
                if content[point[0]][point[1]] == '0' or content[point[0]][point[1]] == 'P':
                    l2.append(point)
            l1.remove(m)
        l1 = l2
        loop = chr(ord(loop) + 1)
        if ord(loop) > (ord('9') + 2):
            loop = chr(ord('2'))
    return content


def check(content):
    pacman = 0
    ghost = 0
    for line in content:
        for c in line:
            if c == 'P':
                pacman += 1
            elif c == 'F':
                ghost += 1
            elif c != '0' and c != '1':
                print("Invalid character %c", c)
                sys.exit(84)
    if pacman != 1 or ghost != 1:
        print("The map need to contain one pacman and one ghost")
        sys.exit(84)


def ghost(content):
    for i in range(0, len(content[0])):
        for j in range(0, len(content[i])):
            if content[i][j] == 'F':
                return [i, j]


def main():
    if len(sys.argv) != 4:
        print("usage: %s file c1 c2", sys.argv[0])
        sys.exit(84)
    if not os.path.isfile(sys.argv[1]):
        print("file %s has not been found", sys.argv[1])
        sys.exit(84)
    c1 = sys.argv[2]
    c2 = sys.argv[3]
    if len(c1) != 1 or len(c2) != 1:
        print("c1 and c2 must be one character")
    c1 = c1[0]
    c2 = c2[0]
    with open(sys.argv[1]) as file:
        content = file.readlines()
    content = list(map(lambda s: s.strip(), content))
    check(content)
    content = pathfinding(content, ghost(content))
    display(content, c1, c2)
    sys.exit(0)


if __name__ == "__main__":
    main()
